### ISSUE TITLE
Help not really helpful; several feature requests

### ISSUE THREAD

**Issue by DerPoet** [Canop/lfs#39]
`--help` does not tell which values are available for `-c`

And I would really appreciate if
- there were an option `--csv`
- I could type abbreviated arguments, e.g. `--units b` or `-c +ino`
- I had an option `--no-bar-graphs` to  leave out the bar graphs
- there were options for restricting/filtering the filesystems shown, e.g. `--type ext4,xfs` or `--no-type tmpfs` or `--min-use 90%` or `--disk lvm,ssd` or maybe something like `--filter 'type=ext4,xfs and disk!=ssd and use>90'`
- there were an option `--no-header` (especially with `--csv`)

**Comment by DerPoet** [comment]
and an option for sorting by any column
and an `--ascii`option for output in plain ascii (for dumber terminals in the n-th login level)

**Comment by Canop** [comment]
So many questions. Let's handle them one per one

1) `--help` does not tell which values are available for `-c`.

That's true. I'm not sure of how I'll handle this without replacing the library I use for arg parsing. In the meantime, I just improved the error message:

![image](https://user-images.githubusercontent.com/617006/155383681-73924fb8-4a51-4f40-b4d5-2e1bf371298b.png)

2) The `--csv` option : No objection. Please make a separate dedicated issue.

3) I'll add other abbreviated column values. Suggestions welcome

4)  `--no-bar-graphs` : It would be some new columns with just the percentages `use_percent` & `inodes_percent`. I note to add those

5) Are those filterings really useful ? If it's for post-treatment you can use jq. What's the reason here ?

6) the `--no-header` option doesn't look terribly useful

7) sorting: see https://github.com/Canop/lfs/issues/37

8) `--ascii` : No objection. Please make a separate dedicated issue.

**Comment by Canop** [comment]
![image](https://user-images.githubusercontent.com/617006/155404436-2cae6d39-157c-44fe-b9a9-c7b5a4eeaaf7.png)

(in the next release)

**Comment by DerPoet** [comment]
Hello Canop,
thank you for your quick response and the work you do!
Even more thanks for implementing so many of the suggestions coming from outside.
As you asked, I've opened separate issues for `--csv` and `--ascii`.

Regarding the filtering: Sure, it's not really **necessary**, jq/grep/awk/... can do the same thing.
It would just be nice to do the filtering within the tool. And it would, for example, avoid mistakes by having a grep matching also an entry in a non-intended column. (The older I become, the more I'm in for safe code, after having seen the weirdest ways that things go wrong. Maybe that's only my personal quirk.)

Best regards,
Christian

**Comment by Canop** [comment]
I'm not at all in favor of grepping the output of lfs, I agree it's too dangerous. The alternative I would use is json + jq.

I'll certainly do the filtering right in lfs if I feel like it would be used by several users. It mostly depends on whether many people start to use lfs and would need this feature. It could be a separate issue and we'd see if people chime in to say they're interested.

**Comment by DerPoet** [comment]
Okay, I've added a comment to #41 .
Thank you.

**Comment by lemmy04** [comment]
I would love to have a proper manpage.

**Comment by Canop** [comment]
@lemmy04  Can you please crate a separate issue for that, so that we don't forget?

**Comment by Canop** [comment]
Most of what's here has been moved to other issues. Closing this one.
